files:
  a-n-astronaut-taking-off-his-helmet-8474624:
    width: 1080
    height: 720
    left: 0
    down: 330
    start: 0
  an-african-elephant-covered-in-mud-11760745:
    width: 4096
    height: 2160
    left: 0
    down: 0
    start: 0
  an-astronaut-sitting-and-looking-around-in-a-desert-8474595:
    width: 1080
    height: 1920
    left: 0
    down: 0
    start: 0
  astronauts-looking-around-in-a-desolate-area-8474604:
    width: 1080
    height: 1920
    left: 0
    down: 0
    start: 0
  claiton-conto-11489108:
    width: 2126
    height: 3778
    left: 0
    down: 0
    start: 0
  footage-of-an-elephant-855538:
    width: 1920
    height: 1080
    left: 0
    down: 0
    start: 0
  river-elephant-elephant-bathing-elephant-in-river-3958529:
    width: 1920
    height: 1080
    left: 0
    down: 0
    start: 0
  roman-odintsov-11760754:
    width: 2160
    height: 4096
    left: 0
    down: 0
    start: 0
  roman-odintsov-11760788:
    width: 2160
    height: 4096
    left: 0
    down: 0
    start: 0
