files:
  a-n-astronaut-taking-off-his-helmet-8474624:
    make: 'n'
    width: 1080
    height: 720
    left: 0
    down: 330
    start: 0
  an-african-elephant-covered-in-mud-11760745:
    make: 'n'
    width: 2525
    height: 1683
    left: 886
    down: 0
    start: 0
  an-astronaut-sitting-and-looking-around-in-a-desert-8474595:
    make: 'n'
    width: 1080
    height: 720
    left: 0
    down: 660
    start: 0
  astronauts-looking-around-in-a-desolate-area-8474604:
    make: 'n'
    width: 1080
    height: 720
    left: 0
    down: 374
    start: 0
  claiton-conto-11489108:
    make: 'n'
    width: 2126
    height: 1417
    left: 0
    down: 956
    start: 0
  river-elephant-elephant-bathing-elephant-in-river-3958529:
    make: 'n'
    width: 1355
    height: 903
    left: 373
    down: 178
    start: 0
  roman-odintsov-11760754:
    make: 'y'
    width: 2160
    height: 1440
    left: 0
    down: 1034
    start: 0
  roman-odintsov-11760788:
    make: 'n'
    width: 2160
    height: 1440
    left: 0
    down: 1310
    start: 0
